### ISSUE TITLE
rsyncd init script not needed on RHEL 7

### ISSUE THREAD

**Issue by erinn** [sous-chefs/rsync#26]
You folks provide an rsyncd init script for RHEL, however, I think (though I am not 100% sure) that that is only needed for RHEL < 7, RHEL7 rsync has systemd unit files for rsync:

`rpm -ql rsync | grep systemd
/usr/lib/systemd/system/rsyncd.service
/usr/lib/systemd/system/rsyncd.socket
/usr/lib/systemd/system/rsyncd@.service`

So if we can set a check in there for RHEL < 7, then we don't end up with multiple init scripts/systemd units.

**Comment by ramereth** [comment]
This will actually get addressed in #43 once merged/released.
